package com.wude.nexusmind.agent.mcp;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.mcp.SyncMcpToolCallbackProvider;
import org.springframework.ai.tool.ToolCallback;
import org.springframework.beans.factory.ObjectProvider;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/** Immutable startup discovery snapshot for configured remote MCP tools. */
public final class McpToolRegistry {

    private static final Logger log = LoggerFactory.getLogger(McpToolRegistry.class);

    private final McpProperties properties;
    private final List<McpDiscoveredTool> discoveredTools;
    private final List<ToolCallback> allowedCallbacks;

    public McpToolRegistry(McpProperties properties,
                           ObjectProvider<SyncMcpToolCallbackProvider> provider,
                           ObjectProvider<McpToolResultBudgeter> resultBudgeterProvider) {
        this.properties = properties;
        if (!properties.enabled()) {
            this.discoveredTools = List.of();
            this.allowedCallbacks = List.of();
            return;
        }

        SyncMcpToolCallbackProvider callbackProvider = provider.getIfAvailable();
        McpToolResultBudgeter resultBudgeter = resultBudgeterProvider.getIfAvailable();
        if (callbackProvider == null || resultBudgeter == null) {
            throw new IllegalStateException(
                    "MCP is enabled but the Spring AI MCP client is unavailable");
        }

        try {
            List<ToolCallback> callbacks = Arrays.stream(callbackProvider.getToolCallbacks())
                    .sorted((left, right) -> left.getToolDefinition().name()
                            .compareTo(right.getToolDefinition().name()))
                    .toList();
            Set<String> names = new HashSet<>();
            for (ToolCallback callback : callbacks) {
                String name = callback.getToolDefinition().name();
                validateExternalName(name);
                if (!names.add(name)) {
                    throw new IllegalStateException("Duplicate MCP tool name: " + name);
                }
            }

            Set<String> allowed = Set.copyOf(properties.allowedTools());
            Set<String> unknown = new HashSet<>(allowed);
            unknown.removeAll(names);
            if (!unknown.isEmpty()) {
                throw new IllegalStateException(
                        "MCP allowlist contains undiscovered tools: " + unknown);
            }

            this.discoveredTools = callbacks.stream()
                    .map(callback -> {
                        String name = callback.getToolDefinition().name();
                        return new McpDiscoveredTool(name, allowed.contains(name));
                    })
                    .toList();
            this.allowedCallbacks = callbacks.stream()
                    .filter(callback -> allowed.contains(callback.getToolDefinition().name()))
                    .map(callback -> (ToolCallback) new BudgetedMcpToolCallback(
                            callback, resultBudgeter, properties))
                    .toList();
            log.info("MCP startup discovery completed: discoveredToolCount={}, allowedToolCount={}",
                    discoveredTools.size(), allowedCallbacks.size());
        } catch (RuntimeException failure) {
            log.error("MCP initialization or tool discovery failed: errorType={}",
                    failure.getClass().getSimpleName());
            throw new IllegalStateException("MCP initialization or tool discovery failed");
        }
    }

    public List<ToolCallback> allowedCallbacks() {
        return allowedCallbacks;
    }

    public McpDiscoveryResponse discovery() {
        return new McpDiscoveryResponse(
                properties.enabled(), discoveredTools.size(), allowedCallbacks.size(), discoveredTools);
    }

    private static void validateExternalName(String name) {
        if (name == null || name.length() > NexusMcpToolNamePrefixGenerator.MAX_NAME_LENGTH
                || !name.matches("mcp_[A-Za-z0-9_]+")) {
            throw new IllegalStateException("Unsafe MCP tool name generated by client integration");
        }
    }
}
